Added 8Bit music to the main game
PendragonGame/pendragon pull request #125
Opened 2017-10-23 22:19 UTC by mike4tin

#114 @anand-bala let me know what you think

2017-10-23 22:48 UTC, anand-bala requested changes
You seem to be committing a new `package-lock.json`. It would be preferable if you replaced this with what was originally in the repo

2017-10-23 22:48 UTC, anand-bala commented on src/app/ui/ui.js
> + <<<<<<< 8bit_music
This is the beginning of a merge conflict. This has not been resolved.

2017-10-23 22:48 UTC, anand-bala commented on src/app/ui/ui.js
> + =======
This is the divider between incoming (your) changes and current file.

2017-10-23 22:48 UTC, anand-bala commented on src/app/ui/ui.js
> + >>>>>>> develop
This is the end of the previously marked conflict. This one is simple, just remove the first section (from the `8bit_music` line to the `===`), and remove the marking lines

2017-10-24 00:15 UTC, anand-bala approved these changes

2017-10-24 00:16 UTC, anand-bala commented
@mike4tin  This works great, but I am going to hold off merging it for a bit. Thanks a tonne.

2017-10-31 00:56 UTC, anand-bala commented
@mike4tin can you fix the merge conflicts?

2017-10-31 01:49 UTC, mike4tin commented
Not sure if I can. I can't open it in terminal like I would normally be able to if it was my repo

2017-11-06 00:50 UTC, anand-bala approved these changes

2017-11-19 18:36 UTC, closed without merging